=== magento/magento2/lib/internal/Magento/Framework/Event/etc/events.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="event" type="eventDeclaration" minOccurs="0" maxOccurs="unbounded">
                    <xs:unique name="uniqueObserverName">
                        <xs:annotation>
                            <xs:documentation>
                                Observer name must be unique.
                            </xs:documentation>
                        </xs:annotation>
                        <xs:selector xpath="observer"/>
                        <xs:field xpath="@name"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueEventName">
            <xs:annotation>
                <xs:documentation>
                    Event name must be unique.
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="event" />
            <xs:field xpath="@name" />
        </xs:unique>
    </xs:element>

    <xs:complexType name="eventDeclaration">
        <xs:annotation>
            <xs:documentation>
                Event declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="observer" type="observerDeclaration" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="eventName" use="required" />
    </xs:complexType>

    <xs:complexType name="observerDeclaration">
        <xs:annotation>
            <xs:documentation>
                Observer declaration.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="instance" type="xs:string" use="optional" />
        <xs:attribute name="disabled" type="xs:boolean" use="optional" />
        <xs:attribute name="shared" type="xs:boolean" use="optional" />
        <xs:attribute name="ifconfig" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:simpleType name="eventName">
        <xs:annotation>
            <xs:documentation>
                Event name can contain only [a-zA-Z0-9_].
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9_]+" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== magento/magento2/app/code/Magento/Customer/etc/events.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Event/etc/events.xsd">
    <event name="customer_address_save_before">
        <observer name="customer_address_before_save_viv_observer" instance="Magento\Customer\Observer\BeforeAddressSaveObserver" />
    </event>
    <event name="customer_address_save_after">
        <observer name="customer_address_after_save_viv_observer" instance="Magento\Customer\Observer\AfterAddressSaveObserver" />
    </event>
    <event name="sales_quote_save_after">
        <observer name="customer_visitor" instance="Magento\Customer\Observer\Visitor\BindQuoteCreateObserver" />
    </event>
    <event name="customer_save_after_data_object">
        <observer name="upgrade_order_customer_email" instance="Magento\Customer\Observer\UpgradeOrderCustomerEmailObserver"/>
        <observer name="upgrade_quote_customer_email" instance="Magento\Customer\Observer\UpgradeQuoteCustomerEmailObserver"/>
        <observer name="clear_quote_session_after_updating_customer" instance="Magento\Customer\Observer\ClearQuoteSessionAfterChangingCustomer"/>
    </event>
    <event name="customer_customer_authenticated">
        <observer name="customerGroupAuthenticate" instance="Magento\Customer\Observer\CustomerGroupAuthenticate" />
    </event>
    <event name="catalog_rule_collection_load_after">
        <observer name="catalogRuleCustomerGroupExcludedWebsite" instance="Magento\Customer\Observer\CatalogRule\AddCustomerGroupExcludedWebsite" />
    </event>
</config>
